import { AttributeDef, ProductDef } from '../interfaces/product-def';
import { Product, ProductAttribute, ProductAttributeValue } from '../../app/shared/interfaces/product';
import { brands } from './brands';
import { Category } from '../../app/shared/interfaces/category';
import { shopCategoriesList } from './categories';
import { Observable, of, throwError, timer } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpErrorResponse } from '@angular/common/http';

let lastProductId = 0;

export const attributesDef: AttributeDef[] = [
    {
        name: 'Color',
        slug: 'color',
        values: [
            { name: 'White', slug: 'white' },
            { name: 'Silver', slug: 'silver' },
            { name: 'Light Gray', slug: 'light-gray' },
            { name: 'Gray', slug: 'gray' },
            { name: 'Dark Gray', slug: 'dark-gray' },
            { name: 'Coal', slug: 'coal' },
            { name: 'Black', slug: 'black' },
            { name: 'Red', slug: 'red' },
            { name: 'Orange', slug: 'orange' },
            { name: 'Yellow', slug: 'yellow' },
            { name: 'Pear Green', slug: 'pear-green' },
            { name: 'Green', slug: 'green' },
            { name: 'Emerald', slug: 'emerald' },
            { name: 'Shamrock', slug: 'shamrock' },
            { name: 'Shakespeare', slug: 'shakespeare' },
            { name: 'Blue', slug: 'blue' },
            { name: 'Dark Blue', slug: 'dark-blue' },
            { name: 'Violet', slug: 'violet' },
            { name: 'Purple', slug: 'purple' },
            { name: 'Cerise', slug: 'cerise' },
        ],
    },
    {
        name: 'Speed',
        slug: 'speed',
        values: [
            { name: '750 RPM', slug: '750-rpm' },
        ],
    },
    {
        name: 'Power Source',
        slug: 'power-source',
        values: [
            { name: 'Cordless-Electric', slug: 'cordless-electric' },
        ],
    },
    {
        name: 'Battery Cell Type',
        slug: 'battery-cell-type',
        values: [
            { name: 'Lithium', slug: 'lithium' },
        ],
    },
    {
        name: 'Voltage',
        slug: 'voltage',
        values: [
            { name: '20 Volts', slug: '20-volts' },
        ],
    },
    {
        name: 'Battery Capacity',
        slug: 'battery-capacity',
        values: [
            { name: '2 Ah', slug: '2-Ah' },
        ],
    },
];

const productsDef: ProductDef[] = [
    {
        used:'Ideal para guardar y transportar herramientas personales',
        slug: 'Caja-de-herramientas-5-gavetas',
        name: 'Caja de Herramientas 5 Gavetas',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Caja_de_herramientas_5_gavetas.png',
            'assets/images/products/Caja_de_herramientas_5_gavetas.png',
        ],
        badges: 'new',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['herramientas'],
        attributes: [
            { slug: 'color', values: 'black' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'Ideal para almacenar y transportar las herramientas de trabajo.',
        slug: 'Caja-de-Herramientas-11',
        name: 'Caja de Herramientas 11DD',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Caja_de_Herramientas_11.png',
            'assets/images/products/Caja_de_Herramientas_11.png',
        ],
        badges: 'new',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'yellow' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'Ideal para guardar herramientas',
        slug: 'Caja-de-Herramientas-Aluminio-3-en-1',
        name: 'Caja de Herramientas de Aluminio',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Caja_de_Herramientas_Aluminio_3_en_1.png',
            'assets/images/products/Caja_de_Herramientas_Aluminio_3_en_1.png',
        ],
        badges: 'new',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'silver' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'Transporte de herramientas',
        slug: 'Caja-Organizadora',
        name: 'Caja Organizadora',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Caja_Organizadora.png',
            'assets/images/products/Caja_Organizadora.png',
        ],
        badges: 'new',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'blue' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Cerradura-Blindada-770',
        name: 'Cerradura Blindada 770',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Cerradura_Blindada_770.png',
            'assets/images/products/Cerradura_Blindada_770.png',
        ],
        badges: 'new',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'black' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Cerradura-Blindada-880',
        name: 'Cerradura Blindada 880',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Cerradura_Blindada_880.png',
            'assets/images/products/Cerradura_Blindada_880.png',
        ],
        badges: 'new',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'yellow' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Cerradura-Blindada-B-940-Dorado',
        name: 'Cerradura Blindada B-940 Dorado',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Cerradura_Blindada_B-940_Dorado.png',
            'assets/images/products/Cerradura_Blindada_B-940_Dorado.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'yellow' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Cerradura-de-Sobreponer-BK-220',
        name: 'Cerradura de Sobreponer BK-220',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Cerradura_de_Sobreponer_BK-220.png',
            'assets/images/products/Cerradura_de_Sobreponer_BK-220.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'yellow' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'cincel-plano',
        name: 'Cincel Plano',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/cincel_plano.png',
            'assets/images/products/cincel_plano.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'blue' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Cincel-Proteccion',
        name: 'Cincel Proteccion',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Cincel_Proteccion.png',
            'assets/images/products/Cincel_Proteccion.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'red' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Comba_1_8 kg',
        name: 'Comba 1.8 kg',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Comba_1_8_kg.png',
            'assets/images/products/Comba_1_8_kg.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'red' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Comba_6_Ib_Profesional',
        name: 'Comba 6 Ib Profesional',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Comba_6_Ib_Profesional.png',
            'assets/images/products/Comba_6_Ib_Profesional.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'red' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Escuadra-job',
        name: 'Escuadra',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Escuadra_job.png',
            'assets/images/products/Escuadra_job.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'silver' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Gabinete-Rodante-2-en-1',
        name: 'Gabinete Rodante 2 en 1',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Gabinete_Rodante_2_en_1.png',
            'assets/images/products/Gabinete_Rodante_2_en_1.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'white' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Huincha-5m',
        name: 'Huincha 5m',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Huincha_5m.png',
            'assets/images/products/Huincha_5m.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'yellow' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Huincha-plastica-con-asa-50m',
        name: 'Huincha plastica con asa 50m',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Huincha_plastica_con_asa_50m.png',
            'assets/images/products/Huincha_plastica_con_asa_50m.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'yellow' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Pack-angulo-pesado-Zincado',
        name: 'Pack angulo pesado Zincado',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Pack_angulo_pesado_Zincado.png',
            'assets/images/products/Pack_angulo_pesado_Zincado.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'silver' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Pegamento-Chemayolic-Block-de-vidrio-10Kg',
        name: 'Pegamento Chemayolic Block de vidrio 10Kg',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Pegamento_Chemayolic_Block_de_vidrio_10Kg.png',
            'assets/images/products/Pegamento_Chemayolic_Block_de_vidrio_10Kg.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'silver' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Pegamento-en-polvo-blanco-25-kg',
        name: 'Pegamento en polvo blanco 25 kg',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Pegamento_en_polvo_blanco_25_kg.png',
            'assets/images/products/Pegamento_en_polvo_blanco_25_kg.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'white' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Pegamento-en-polvo-Chemayolic-25kg',
        name: 'Pegamento en polvo Chemayolic 25kg',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Pegamento_en_polvo_Chemayolic_25kg.png',
            'assets/images/products/Pegamento_en_polvo_Chemayolic_25kg.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'white' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Pegamento-en-polvo-gris-25-kilos',
        name: 'Pegamento en polvo gris 25 kilos',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Pegamento_en_polvo_gris_25_kilos.png',
            'assets/images/products/Pegamento_en_polvo_gris_25_kilos.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Pegamento-en-polvo-Gris-Interiores-25-Kg',
        name: 'Pegamento en polvo Gris Interiores 25 Kg',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Pegamento_en_polvo_Gris_Interiores_25_Kg.png',
            'assets/images/products/Pegamento_en_polvo_Gris_Interiores_25_Kg.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Porcelanato-Cement-60x60cm',
        name: 'Porcelanato Cement 60x60cm',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Porcelanato_Cement_60x60cm.png',
            'assets/images/products/Porcelanato_Cement_60x60cm.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Porcelanato-concrete-taupe',
        name: 'Porcelanato concrete taupe',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Porcelanato_concrete_taupe.png',
            'assets/images/products/Porcelanato_concrete_taupe.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Porcelanato-Crystal-Blanco',
        name: 'Porcelanato Crystal Blanco',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Porcelanato_Crystal_Blanco.png',
            'assets/images/products/Porcelanato_Crystal_Blanco.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Porcelanato-gris',
        name: 'Porcelanato Gris',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Porcelanato_gris.png',
            'assets/images/products/Porcelanato_gris.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Regla-de-Aluminio-5-85-m',
        name: 'Regla de Aluminio 5.85m',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Regla_de_Aluminio_5_85_m.png',
            'assets/images/products/Regla_de_Aluminio_5_85_m.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Set-de-Punzones-y-Cinceles',
        name: 'Set de Punzones y Cinceles',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/Set_de_Punzones_y_Cinceles.png',
            'assets/images/products/Set_de_Punzones_y_Cinceles.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['screwdrivers'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'bandas-de-lija',
        name: 'Bandas de Lija',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/1bandas_de_lija.png',
            'assets/images/products/1bandas_de_lija.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['lijas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Broca-xmm',
        name: 'Broca xmm',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/1Broca.png',
            'assets/images/products/1Broca.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['brocas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'cincel-xmm',
        name: 'Cincel xmm',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/1cincel.png',
            'assets/images/products/1cincel.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['cinceles'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Clavo-calaminero',
        name: 'Clavo Calaminero',
        price: parseInt((Math.random() * 999).toString()),
        images: [
            'assets/images/products/1Clavo_calaminero.png',
            'assets/images/products/1Clavo_calaminero.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['cinceles'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Clavos-albañil',
        name: 'Clavos Albañil',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Clavos_albañil.png',
            'assets/images/products/1Clavos_albañil.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['cinceles'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Conmutador-doble',
        name: 'Conmutador Doble',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Conmutador_doble.png',
            'assets/images/products/1Conmutador_doble.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['cinceles'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Conmutador-doble-sp',
        name: 'Conmutador Doble SP',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Conmutador_doble_sp.png',
            'assets/images/products/1Conmutador_doble_sp.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['cinceles'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Disco-diamantado',
        name: 'Disco Diamantado',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Disco_diamantado.png',
            'assets/images/products/1Disco_diamantado.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['cinceles'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Interrumptor',
        name: 'Interrumptor',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Interrumptor.png',
            'assets/images/products/1Interrumptor.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['cinceles'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'interrumptor-simple',
        name: 'Interrumptor Simple',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1interrumptor_simple.png',
            'assets/images/products/1interrumptor_simple.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['cinceles'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'juego-de-brocas',
        name: 'Juego de Brocas',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1juego_de_brocas.png',
            'assets/images/products/1juego_de_brocas.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['cinceles'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Latex-Deluxe',
        name: 'Latex Deluxe',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Latex_Deluxe.png',
            'assets/images/products/1Latex_Deluxe.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['pinturas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Latex-Premium',
        name: 'Latex Premium',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Latex_Premium.png',
            'assets/images/products/1Latex_Premium.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['pinturas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Latex-Standard',
        name: 'Latex Standard',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Latex_Standard.png',
            'assets/images/products/1Latex_Standard.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['pinturas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'martillo-albañil',
        name: 'Martillo Albañil',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1martillo_albañil.png',
            'assets/images/products/1martillo_albañil.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['pinturas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'martillo-antivibracion',
        name: 'Martillo Antivibracion',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1martillo_antivibracion.png',
            'assets/images/products/1martillo_antivibracion.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['pinturas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Martillo-goma',
        name: 'Martillo Goma',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Martillo_jebe.png',
            'assets/images/products/1Martillo_jebe.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['pinturas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'martillo-madera',
        name: 'Martillo Madera',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1martillo_madera.png',
            'assets/images/products/1martillo_madera.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['pinturas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'martillo-mango',
        name: 'Martillo mango',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1martillo_mango.png',
            'assets/images/products/1martillo_mango.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['pinturas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'pack-100-clavos',
        name: 'Pack 100 Clavos',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1pack_100clavos.png',
            'assets/images/products/1pack_100clavos.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['pinturas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Pack-50-clavos',
        name: 'Pack 50 Clavos',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Pack_x_50_clavos.png',
            'assets/images/products/1Pack_x_50_clavos.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['pinturas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Pintura-Almendra',
        name: 'Pintura Almendra',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Pintura_Almendra.png',
            'assets/images/products/1Pintura_Almendra.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['pinturas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Pintura-Latex',
        name: 'Pintura Latex',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Pintura_Latex.png',
            'assets/images/products/1Pintura_Latex.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['pinturas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Placa',
        name: 'Placa',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Placa.png',
            'assets/images/products/1Placa.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['pinturas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Serrucho-costilla',
        name: 'Serrucho Costilla',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1serrucho_costilla.png',
            'assets/images/products/1serrucho_costilla.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['pinturas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'serrucho-isosceles',
        name: 'Serrucho Isosceles',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1serrucho_isosceles.png',
            'assets/images/products/1serrucho_isosceles.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['pinturas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Serrucho-Luctador',
        name: 'Serrucho Luctador',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Serrucho_Luctador.png',
            'assets/images/products/1Serrucho_Luctador.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['pinturas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'serrucho-luctador-16',
        name: 'Serrucho Luctador 16',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1serrucho_luctador_16.png',
            'assets/images/products/1serrucho_luctador_16.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['pinturas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'serrucho-mango',
        name: 'Serrucho Mango',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1serrucho_mango.png',
            'assets/images/products/1serrucho_mango.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['pinturas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Tachuela',
        name: 'Tachuela',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Tachuela.png',
            'assets/images/products/1Tachuela.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['pinturas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Taladro-atornillador',
        name: 'Taladro Atornillador',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Taladro_atornillador.png',
            'assets/images/products/1Taladro_atornillador.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['herramientas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Taladro-Atornillador-inalambrico',
        name: 'Taladro Atornillador Inalambrico',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Taladro_Atornillador_inalambrico.png',
            'assets/images/products/1Taladro_Atornillador_inalambrico.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['herramientas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Taladro-Percutor',
        name: 'Taladro Percutor',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Taladro_Percutor.png',
            'assets/images/products/1Taladro_Percutor.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['herramientas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Taladro-Percutor-Bosh',
        name: 'Taladro Percutor Bosh',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Taladro_Percutor_Bosh.png',
            'assets/images/products/1Taladro_Percutor_Bosh.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['herramientas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Taladro-Percutor-Bosh',
        name: 'Taladro Percutor Bosh',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Taladro_Percutor_Bosh.png',
            'assets/images/products/1Taladro_Percutor_Bosh.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['herramientas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Taladro-Percutor-Inalambrico',
        name: 'Taladro Percutor Inalambrico',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Taladro_Percutor_Inalambrico.png',
            'assets/images/products/1Taladro_Percutor_Inalambrico.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['herramientas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Válvula-check',
        name: 'Válvula Check',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Válvula_check.png',
            'assets/images/products/1Válvula_check.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['herramientas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Válvulas-roedores',
        name: 'Válvulas Roedores',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Válvulas_roedores.png',
            'assets/images/products/1Válvulas_roedores.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['herramientas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Válvula-compuerta',
        name: 'Válvula Compuerta',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Válvula_compuerta.png',
            'assets/images/products/1Válvula_compuerta.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['herramientas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Válvula-esférica',
        name: 'Válvula Esférica',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Válvula_esférica.png',
            'assets/images/products/1Válvula_esférica.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['herramientas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    },
    {
        used:'xxxxxxxxxx',
        slug: 'Válvula-flotadora',
        name: 'Válvula Flotadora',
        price: parseInt((Math.random() * 999).toFixed(2)),
        images: [
            'assets/images/products/1Válvula_flotadora.png',
            'assets/images/products/1Válvula_flotadora.png',
        ],
        badges: 'hot',
        rating: parseInt((Math.random() * 20).toString()),
        reviews: parseInt((Math.random() * 20).toString()),
        availability: 'in-stock',
        brand: 'brandix',
        categories: ['herramientas'],
        attributes: [
            { slug: 'color', values: 'gray' },
            { slug: 'speed', values: '750-rpm', featured: true },
            { slug: 'power-source', values: 'cordless-electric', featured: true },
            { slug: 'battery-cell-type', values: 'lithium', featured: true },
            { slug: 'voltage', values: '20-volts', featured: true },
            { slug: 'battery-capacity', values: '2-Ah', featured: true },
        ],
    }
];

export const products: Product[] = productsDef.map(productDef => {
    let badges = [];

    if (productDef.badges) {
        badges = typeof productDef.badges === 'string' ? [productDef.badges] : productDef.badges;
    }

    const categories: Category[] = shopCategoriesList.filter(x => productDef.categories.includes(x.slug)).map(x => ({
        ...x,
        parents: null,
        children: null,
    }));

    const attributes: ProductAttribute[] = (productDef.attributes || []).map(productAttributeDef => {
        const attributeDef = attributesDef.find(x => x.slug === productAttributeDef.slug);

        if (!attributeDef) {
            return null;
        }

        let valuesDef: string[] = [];

        if (typeof productAttributeDef.values === 'string') {
            valuesDef = [productAttributeDef.values];
        } else if (productAttributeDef.values) {
            valuesDef = productAttributeDef.values;
        }

        const values: ProductAttributeValue[] = valuesDef.map(valueSlug => {
            const valueDef = attributeDef.values.find(x => x.slug === valueSlug);

            if (!valueDef) {
                return null;
            }

            return {
                ...valueDef,
                customFields: {},
            };
        }).filter(x => x !== null);

        if (!values.length) {
            return null;
        }

        return {
            name: attributeDef.name,
            slug: attributeDef.slug,
            featured: !!productAttributeDef.featured,
            values,
            customFields: {},
        };
    }).filter(x => x !== null);

    return {
        id: ++lastProductId,
        name: productDef.name,
        used: productDef.used,
        sku: '83690/32',
        slug: productDef.slug,
        price: productDef.price,
        compareAtPrice: productDef.compareAtPrice || null,
        images: productDef.images.slice(),
        badges: badges.slice(),
        rating: productDef.rating,
        reviews: productDef.reviews,
        availability: productDef.availability,
        brand: brands.find(x => x.slug === productDef.brand) || null,
        categories,
        attributes,
        customFields: {},
    };
});

export function getBestsellers(limit: number = null): Observable<Product[]> {
    const start = 0;
    const end = limit ? start + limit : undefined;

    return of(products.slice(start, end));
}

export function getTopRated(limit: number = null): Observable<Product[]> {
    const start = 3;
    const end = limit ? start + limit : undefined;

    return of(products.slice(start, end));
}

export function getSpecialOffers(limit: number = null): Observable<Product[]> {
    const start = 6;
    const end = limit ? start + limit : undefined;

    return of(products.slice(start, end));
}

export function getFeatured(categorySlug: string = null, limit: number = null): Observable<Product[]> {
    let fakeProducts = products.slice();

    if (categorySlug === 'power-tools') {
        fakeProducts = fakeProducts.reverse();
    } else if (categorySlug === 'hand-tools') {
        fakeProducts = [...fakeProducts.slice(8), ...fakeProducts.slice(0, 8)];
    } else if (categorySlug === 'plumbing') {
        fakeProducts = [...fakeProducts.slice(8), ...fakeProducts.slice(0, 8)].reverse();
    }

    return timer(1000).pipe(map(() => fakeProducts.slice(0, limit || undefined)));
}

export function getLatestProducts(categorySlug: string = null, limit: number = null): Observable<Product[]> {
    return getFeatured(categorySlug, limit);
}

// noinspection JSUnusedLocalSymbols
export function getRelatedProducts(product: Partial<Product>): Observable<Product[]> {
    return of(products.slice(0, 7));
}

export function getSuggestions(query: string, limit: number, categorySlug: string = null): Observable<Product[]> {
    return of(products.filter(x => x.name.toLowerCase().includes(query.toLowerCase())).slice(0, limit));
}

export function getProduct(productSlug: string): Observable<Product> {
    const product = products.find(x => x.slug === productSlug);

    if (!product) {
        return throwError(new HttpErrorResponse({ status: 404, statusText: 'Page Not Found' }));
    }

    return of(JSON.parse(JSON.stringify(product)));
}
